### ISSUE TITLE
stdlib/site 변수에 대한 UnboundLocalError 예외

### ISSUE THREAD

**Issue by allieus** [spoqa/import-order#1]
https://github.com/spoqa/import-order/blob/master/import_order/sort.py#L40 에서 stdlib/site 변수에 대해 UnboundLocalError 예외가 발생하는 케이스가 있습니다.

https://github.com/spoqa/import-order/blob/master/import_order/sort.py#L37 에서 ImportError 발생 시에 대한 처리도 해줘야 되지 않을까요?

```
try:
    pass
except ImportError:
    stdlib = False
    site = False
```

**Comment by kanghyojun** [comment]
넵 실수로 흘러 들어간 코드인데요. `ImportError`를 잡지않고 패스시키면 `import-order` 실행시켰을때 없는 패키지를 볼 수 있게됩니다. 지금 막 고치고있었습니다 ㅎㅎ.
