### ISSUE TITLE
Give options to decide priority between `from ... import ....` and `import ...`

### ISSUE THREAD

**Issue by kanghyojun** [spoqa/import-order#19]
Usually, i want to differentiate two import statements like below

```
from b import x
from d import y
import c
```

but `import-order` force to write import statements in alphabetical order, wheter import statements are diffrent or not.

**Comment by AiOO** [comment]
This issue has been resolved from [0.0.7](https://github.com/spoqa/import-order/releases/tag/0.0.7).
