### ISSUE TITLE
import-order inform wrong order with standard libaray

### ISSUE THREAD

**Issue by item4** [spoqa/import-order#2]
I tested it with [cliche](https://github.com/clicheio/cliche) source.

and result contain some wrong order.

Case 1.

```
./cliche/migrations/env.py:1-4: cliche.orm.Base must be the first, not alembic.context
1 from alembic import context
2 from sqlalchemy import engine_from_config, pool
3 
4 from cliche.orm import Base
```

Case 2.

```
./cliche/web/ontology.py:11-13: cliche.sqltypes.HashableLocale must be the first, not itertools
11 import itertools
12 
13 from cliche.sqltypes import HashableLocale as Locale
```

Case 3.

```
./deploy/etc/wsgi.py:1-4: cliche.config.read_config must be the first, not pathlib
1 import pathlib
2 
3 from cliche.web.app import app, setup_sentry
4 from cliche.config import read_config
```

Case 4.

```
./tests/cli_test.py:1-3: cliche.cli.cli must be the first, not subprocess
1 import subprocess
2 
3 from cliche.cli import cli, runserver, shell, upgrade
```

Case 5.

```
./tests/conftest.py:1-11: cliche.celery.app must be the first, not datetime
 1 import datetime
 2 import os
 3 import pathlib
 4 import types
 5 
 6 from click.testing import CliRunner
 7 from pytest import fixture, skip, yield_fixture
 8 from sqlalchemy.sql.functions import now
 9 from yaml import dump
10 
11 from cliche.celery import app as celery_app
```

Case 6.

```
./tests/crawler_test.py:1-6: cliche.services.wikipedia.crawler must be the first, not json
1 import json
2 import os.path
3 
4 from sqlalchemy.sql.expression import func
5 
6 from cliche.services.wikipedia import crawler as dbpedia
```

... and so on. (too many!)

I think it misdetect standard libaray.

**Comment by kanghyojun** [comment]
In case1, `cliche.orm.Base` treat like third-party library although `cliche` is local package. because it is a absolute-import. Other cases, however, it looks like a bug. thx for your reporting :).

**Comment by kanghyojun** [comment]
@item4 it seems like you typed `.` or relative path `./cliche`,

```
$ import-order . # or import-order ./cliche
```

**Comment by item4** [comment]
@admire93 I used `import-order .`. Can't I use relative path?

**Comment by kanghyojun** [comment]
@item4 no you can't. but i think it is useful to inspect relatvie path, absolute path and python file.

**Comment by kanghyojun** [comment]
@item4 it will be patched soon(in 1~2 days). but you have to pass your local package name with relative path (eg. `import-order cliche .`) because there is no function like auto local package detecting.

**Comment by kanghyojun** [comment]
@item4 0.0.2 released and you can use relatvive path with local package names. `import-order cliche .`
