### ISSUE TITLE
TypeError: unorderable types: bool() < NoneType()

### ISSUE THREAD

**Issue by AiOO** [spoqa/import-order#9]
`canonical_sort_key` return type is `(int, str, optional(bool), optional(boo), str)`, however `bool` is not comperable with `None`.

below 2 tuple cannot be orderable.

```
a = (1, 're', None, None, 'compile')
b = (1, 're', True, True, 'compile')
```

**Comment by dahlia** [comment]
[This behavior](https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons) is one of key differences between Python 2 and 3.

**Comment by kanghyojun** [comment]
:+1:
